#!/bin/bash
source lib/linux
source lib/wireless
CORES=`nproc`
UP="../patches"
RED="\e[1;31m"
GRN="\e[1;32m"
YLW="\e[1;33m"
PNK="\e[1;35m"
WHT="\e[1;37m"
FIN="\e[0m"
userdata () {
echo ""
echo -e "${RED}Please create a userdata file${FIN}."
while [ true ] ; do
read -t 7 -n 1
if [ $? = 0 ] ; then
exit ;
else
echo -e "${WHT}run make config${FIN}"
fi
done
}

if ls userdata.txt > /dev/null 2>&1;
	then echo "" && echo -e "${GRN}userdata file found${FIN}.";
	else userdata;
fi
source userdata.txt
mkdir -p linux
cp userdata.txt linux/
cd linux
clean
echo
download
extract
setup
echo
userpatches
sed_name
defconfig
if `grep -Fx "menuconfig=1" "../userdata.txt" >/dev/null;`
    then menuconfig ;
fi
builddeb
