#!/bin/bash
source lib/linux
source userdata.txt
CORES=`nproc`
UP="../patches"
RED="\e[1;31m"
GRN="\e[1;32m"
YLW="\e[1;33m"
FIN="\e[0m"
UD="userdata.txt"
userdata () {
echo ""
echo "Please create a userdata.txt file"
while [ true ] ; do
read -t 20 -n 1
if [ $? = 0 ] ; then
exit ;
else
echo "run make config"
fi
done
}

if [ -f "$UD" ]; then
    echo ""
    echo -e "${GRN}$UD file found${FIN}."
else 
    userdata
fi
mkdir -p linux
cp userdata.txt linux/
cd linux
clean
echo
download
extract
setup
echo
userpatches
defconfig
if `grep -Fx "menuconfig=1" "../userdata.txt" >/dev/null;`
    then menuconfig ;
fi
builddeb